server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /api/v1

spring:
  application:
    name: playpadel
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
  datasource:
    url: jdbc:postgresql://dpg-cu8llhjqf0us73d3rj3g-a.frankfurt-postgres.render.com/playpadeldb
    username: playpadeldb_user
    password: Psw3BdNqUHPiVyyuuUgUYOlM88DJEUaZ
    driver-class-name: org.postgresql.Driver
    tomcat:
      initial-size: 10
      max-active: 30
  jpa:
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    change-log: classpath:db/liquibase-changelog-master.xml
